# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ChooseOrgWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chooseOrgWidget(object):
    def setupUi(self, chooseOrgWidget):
        chooseOrgWidget.setObjectName("chooseOrgWidget")
        chooseOrgWidget.resize(399, 113)
        self.label = QtWidgets.QLabel(chooseOrgWidget)
        self.label.setGeometry(QtCore.QRect(11, 21, 120, 23))
        self.label.setObjectName("label")
        self.organizationComboBox = QtWidgets.QComboBox(chooseOrgWidget)
        self.organizationComboBox.setGeometry(QtCore.QRect(134, 21, 251, 25))
        self.organizationComboBox.setObjectName("organizationComboBox")
        self.widget = QtWidgets.QWidget(chooseOrgWidget)
        self.widget.setGeometry(QtCore.QRect(10, 70, 221, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.widget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.widget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)

        self.retranslateUi(chooseOrgWidget)
        QtCore.QMetaObject.connectSlotsByName(chooseOrgWidget)

    def retranslateUi(self, chooseOrgWidget):
        _translate = QtCore.QCoreApplication.translate
        chooseOrgWidget.setWindowTitle(_translate("chooseOrgWidget", "选择组织"))
        self.label.setText(_translate("chooseOrgWidget", "请选择一个组织："))
        self.okButton.setText(_translate("chooseOrgWidget", "确定"))
        self.cancelButton.setText(_translate("chooseOrgWidget", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chooseOrgWidget = QtWidgets.QWidget()
    ui = Ui_chooseOrgWidget()
    ui.setupUi(chooseOrgWidget)
    chooseOrgWidget.show()
    sys.exit(app.exec_())
