# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/AddFace.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddFaceWidget(object):
    def setupUi(self, AddFaceWidget):
        AddFaceWidget.setObjectName("AddFaceWidget")
        AddFaceWidget.resize(730, 242)
        self.userImageLabel = QtWidgets.QLabel(AddFaceWidget)
        self.userImageLabel.setGeometry(QtCore.QRect(310, 20, 256, 192))
        self.userImageLabel.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.userImageLabel.setText("")
        self.userImageLabel.setObjectName("userImageLabel")
        self.widget = QtWidgets.QWidget(AddFaceWidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 51, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.widget1 = QtWidgets.QWidget(AddFaceWidget)
        self.widget1.setGeometry(QtCore.QRect(90, 20, 201, 211))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameEdit = QtWidgets.QLineEdit(self.widget1)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_2.addWidget(self.nameEdit)
        self.numberEdit = QtWidgets.QLineEdit(self.widget1)
        self.numberEdit.setObjectName("numberEdit")
        self.verticalLayout_2.addWidget(self.numberEdit)
        self.ageEdit = QtWidgets.QLineEdit(self.widget1)
        self.ageEdit.setObjectName("ageEdit")
        self.verticalLayout_2.addWidget(self.ageEdit)
        self.sexComboBox = QtWidgets.QComboBox(self.widget1)
        self.sexComboBox.setObjectName("sexComboBox")
        self.sexComboBox.addItem("")
        self.sexComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.sexComboBox)
        self.widget2 = QtWidgets.QWidget(AddFaceWidget)
        self.widget2.setGeometry(QtCore.QRect(590, 30, 82, 171))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chooseImageBtn = QtWidgets.QPushButton(self.widget2)
        self.chooseImageBtn.setObjectName("chooseImageBtn")
        self.verticalLayout_3.addWidget(self.chooseImageBtn)
        self.saveBtn = QtWidgets.QPushButton(self.widget2)
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout_3.addWidget(self.saveBtn)
        self.exitBtn = QtWidgets.QPushButton(self.widget2)
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout_3.addWidget(self.exitBtn)

        self.retranslateUi(AddFaceWidget)
        QtCore.QMetaObject.connectSlotsByName(AddFaceWidget)

    def retranslateUi(self, AddFaceWidget):
        _translate = QtCore.QCoreApplication.translate
        AddFaceWidget.setWindowTitle(_translate("AddFaceWidget", "人脸信息录入"))
        self.label.setText(_translate("AddFaceWidget", "姓名："))
        self.label_2.setText(_translate("AddFaceWidget", "编号："))
        self.label_3.setText(_translate("AddFaceWidget", "年龄："))
        self.label_4.setText(_translate("AddFaceWidget", "性别："))
        self.sexComboBox.setItemText(0, _translate("AddFaceWidget", "男"))
        self.sexComboBox.setItemText(1, _translate("AddFaceWidget", "女"))
        self.chooseImageBtn.setText(_translate("AddFaceWidget", "选择图片"))
        self.saveBtn.setText(_translate("AddFaceWidget", "保存"))
        self.exitBtn.setText(_translate("AddFaceWidget", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddFaceWidget = QtWidgets.QWidget()
    ui = Ui_AddFaceWidget()
    ui.setupUi(AddFaceWidget)
    AddFaceWidget.show()
    sys.exit(app.exec_())
