# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/AddOrgnization.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddOrgnizationWidget(object):
    def setupUi(self, AddOrgnizationWidget):
        AddOrgnizationWidget.setObjectName("AddOrgnizationWidget")
        AddOrgnizationWidget.resize(389, 225)
        self.widget = QtWidgets.QWidget(AddOrgnizationWidget)
        self.widget.setGeometry(QtCore.QRect(20, 40, 77, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.widget1 = QtWidgets.QWidget(AddOrgnizationWidget)
        self.widget1.setGeometry(QtCore.QRect(120, 20, 221, 151))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameEdit = QtWidgets.QLineEdit(self.widget1)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_2.addWidget(self.nameEdit)
        self.ownerEdit = QtWidgets.QLineEdit(self.widget1)
        self.ownerEdit.setObjectName("ownerEdit")
        self.verticalLayout_2.addWidget(self.ownerEdit)
        self.widget2 = QtWidgets.QWidget(AddOrgnizationWidget)
        self.widget2.setGeometry(QtCore.QRect(20, 180, 168, 33))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveBtn = QtWidgets.QPushButton(self.widget2)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.exitBtn = QtWidgets.QPushButton(self.widget2)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)

        self.retranslateUi(AddOrgnizationWidget)
        QtCore.QMetaObject.connectSlotsByName(AddOrgnizationWidget)

    def retranslateUi(self, AddOrgnizationWidget):
        _translate = QtCore.QCoreApplication.translate
        AddOrgnizationWidget.setWindowTitle(_translate("AddOrgnizationWidget", "添加组织"))
        self.label.setText(_translate("AddOrgnizationWidget", "组织名称："))
        self.label_2.setText(_translate("AddOrgnizationWidget", "负责人："))
        self.saveBtn.setText(_translate("AddOrgnizationWidget", "保存"))
        self.exitBtn.setText(_translate("AddOrgnizationWidget", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddOrgnizationWidget = QtWidgets.QWidget()
    ui = Ui_AddOrgnizationWidget()
    ui.setupUi(AddOrgnizationWidget)
    AddOrgnizationWidget.show()
    sys.exit(app.exec_())
