# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/OrgEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_orgEdit(object):
    def setupUi(self, orgEdit):
        orgEdit.setObjectName("orgEdit")
        orgEdit.resize(582, 510)
        self.label = QtWidgets.QLabel(orgEdit)
        self.label.setGeometry(QtCore.QRect(30, 60, 30, 23))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.orgListView = QtWidgets.QListView(orgEdit)
        self.orgListView.setGeometry(QtCore.QRect(20, 90, 191, 341))
        self.orgListView.setObjectName("orgListView")
        self.memberListView = QtWidgets.QListView(orgEdit)
        self.memberListView.setGeometry(QtCore.QRect(270, 90, 191, 341))
        self.memberListView.setObjectName("memberListView")
        self.label_2 = QtWidgets.QLabel(orgEdit)
        self.label_2.setGeometry(QtCore.QRect(270, 60, 60, 23))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.addMemberBtn = QtWidgets.QPushButton(orgEdit)
        self.addMemberBtn.setGeometry(QtCore.QRect(480, 100, 89, 25))
        self.addMemberBtn.setObjectName("addMemberBtn")
        self.delMemberBtn = QtWidgets.QPushButton(orgEdit)
        self.delMemberBtn.setGeometry(QtCore.QRect(480, 150, 89, 25))
        self.delMemberBtn.setObjectName("delMemberBtn")

        self.retranslateUi(orgEdit)
        QtCore.QMetaObject.connectSlotsByName(orgEdit)

    def retranslateUi(self, orgEdit):
        _translate = QtCore.QCoreApplication.translate
        orgEdit.setWindowTitle(_translate("orgEdit", "编辑组织"))
        self.label.setText(_translate("orgEdit", "组织"))
        self.label_2.setText(_translate("orgEdit", "当前成员"))
        self.addMemberBtn.setText(_translate("orgEdit", "增加"))
        self.delMemberBtn.setText(_translate("orgEdit", "删除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    orgEdit = QtWidgets.QWidget()
    ui = Ui_orgEdit()
    ui.setupUi(orgEdit)
    orgEdit.show()
    sys.exit(app.exec_())
